# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-18 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='云厂商名称')),
                ('code', models.CharField(max_length=25, verbose_name='云厂商简称')),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceId', models.CharField(db_index=True, max_length=100, verbose_name='实例ID')),
                ('instanceType', models.CharField(max_length=20, verbose_name='实例类型')),
                ('cpu', models.CharField(max_length=32, verbose_name='cpu')),
                ('memory', models.CharField(max_length=32, verbose_name='memory')),
                ('instanceName', models.CharField(db_index=True, max_length=32, verbose_name='实例名称')),
                ('createdTime', models.DateTimeField(verbose_name='实例创建时间')),
                ('expiredTime', models.DateTimeField(verbose_name='实例到期时间')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Cloud')),
            ],
        ),
        migrations.AddField(
            model_name='ip',
            name='inner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innerIpAddress', to='resources.Server', verbose_name='内网IP'),
        ),
        migrations.AddField(
            model_name='ip',
            name='public',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicIpAddress', to='resources.Server', verbose_name='外网IP'),
        ),
    ]
