# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='型号')),
            ],
        ),
        migrations.CreateModel(
            name='ZhiZao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='制造商')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='zhizao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ZhiZao'),
        ),
    ]
